### ISSUE TITLE
Can not save polygon

### ISSUE THREAD

**Issue by se7oluti0n** [lzx1413/labelImg#1]
Hi, I have trouble with you app when trying to create a polygon in segmentation mode.
This is the error
```bash
Traceback (most recent call last):
  File "/home/manhattan/new_workplace/annotation/labelImgPlus/libs/canvas.py", line 200, in mousePressEvent
    self.line[0] = self.current[-1]
TypeError: 'NoneType' object has no attribute '__getitem__'

```
I found this may be a bug, and I fixed in file `canvas.py` in line 200
from 
```
if self.current.isClosed():
     self.finalise()
self.line[0] = self.current[-1]
```
This is bug because if you call `self.finalise()` the `self.current` become `None`. 
So I fixed to below and it seemed to work
```
self.line[0] = self.current[-1]
if self.current.isClosed():
     self.finalise()
```

**Comment by lzx1413** [comment]
thanks, I will update the code
