### ISSUE TITLE
Error: Create RectBox

### ISSUE THREAD

**Issue by pogilon** [lzx1413/labelImg#3]
Hello,

When I create a RecBox, I get the error below. I can't therefore save the document and the box disappears after changing the image.
"
Traceback (most recent call last):
  File "labelImg.py", line 1124, in newShape
    self.actions.create.setEnabled(True)
AttributeError: 'struct' object has no attribute 'create'
"

**Comment by se7oluti0n** [comment]
I think line 1124 in `labelImg.py` should be changed to : 
```python
self.actions.createMode.setEnabled(True)
```
